"use client";
import { useState } from "react";

type Block = { id: string; type: "text" | "image" | "button" | "columns" | "divider" | "html"; content: string; settings?: Record<string, unknown> };
type Page = { id: string; title: string; slug: string; status: "Draft" | "Published" | "Archived"; templateId?: string; blocks: Block[]; metadata?: Record<string, unknown>; updatedAt: string };
type Template = { id: string; name: string; slug: string; description: string; blocks: Block[]; layoutId?: string };
type Layout = { id: string; name: string; slug: string; regions: string[]; rules: { fontFamily: string; headingScale: string; accent: string; maxWidth: string; spacing: string; radius: string } };

const id = (prefix: string) => prefix + Math.random().toString(16).slice(2, 8).toUpperCase();
export function VisualCanvas({ pages, templates, layouts, createPage, updatePage, removePage, createTemplate, removeTemplate, updateLayout }: { pages: Page[]; templates: Template[]; layouts: Layout[]; createPage: (page: Page) => void; updatePage: (page: Page) => void; removePage: (page: Page) => void; createTemplate: (template: Template) => void; removeTemplate: (template: Template) => void; updateLayout: (layout: Layout) => void }) {
  const [selectedId, setSelectedId] = useState(pages[0]?.id || "");
  const [selectedBlockId, setSelectedBlockId] = useState("");
  const [dragged, setDragged] = useState<number>();
  const [newType, setNewType] = useState<Block["type"]>("text");
  const [newContent, setNewContent] = useState("");
  const [templateName, setTemplateName] = useState("");
  const [previewWidth, setPreviewWidth] = useState("1180px");
  const page = pages.find((item) => item.id === selectedId) || pages[0];
  const block = page?.blocks.find((item) => item.id === selectedBlockId);
  const save = (next: Page) => updatePage({ ...next, updatedAt: new Date().toISOString() });
  const addBlock = () => { if (!page || !newContent.trim()) return; const next: Block = { id: id("blk_"), type: newType, content: newContent.trim(), settings: newType === "button" ? { url: "/", align: "left" } : { align: "left", color: "#202326" } }; save({ ...page, blocks: [...page.blocks, next] }); setSelectedBlockId(next.id); setNewContent(""); };
  const reorder = (to: number) => { if (!page || dragged === undefined || dragged === to) return; const blocks = [...page.blocks]; const [item] = blocks.splice(dragged, 1); blocks.splice(to, 0, item); save({ ...page, blocks }); setDragged(undefined); };
  const updateBlock = (next: Block) => { if (!page) return; save({ ...page, blocks: page.blocks.map((item) => item.id === next.id ? next : item) }); };
  const createBlank = () => { const next: Page = { id: id("page_"), title: "Untitled page", slug: "untitled-" + Date.now().toString(36), status: "Draft", blocks: [], updatedAt: new Date().toISOString() }; createPage(next); setSelectedId(next.id); };
  const apply = (template: Template) => { if (!page) return; save({ ...page, templateId: template.id, status: "Draft", blocks: template.blocks.map((item) => ({ ...item, id: id("blk_") })) }); };
  return <div className="page visual-builder-page">
    <div className="page-heading compact"><div><p className="kicker">VISUAL STUDIO</p><h1>Pages</h1><p className="subhead">Build with blocks, inspect every property and preview the responsive result.</p></div><button className="primary-button" onClick={createBlank}>＋ New page</button></div>
    <div className="builder-shell">
      <aside className="card builder-pages"><div className="card-heading"><div><p className="eyebrow">PAGES</p><h2>Library</h2></div></div>{pages.map((item) => <div className="builder-page-item" key={item.id}><button className={item.id === page?.id ? "selected" : ""} onClick={() => { setSelectedId(item.id); setSelectedBlockId(item.blocks[0]?.id || ""); }}><b>{item.title}</b><small>/{item.slug} · {item.status}</small></button><button className="text-button" onClick={() => removePage(item)}>Delete</button></div>)}</aside>
      <section className="card builder-canvas"><div className="card-heading"><div><p className="eyebrow">CANVAS</p><h2>{page?.title || "Select a page"}</h2></div>{page && <select value={page.status} onChange={(event) => save({ ...page, status: event.target.value as Page["status"] })}><option>Draft</option><option>Published</option><option>Archived</option></select>}</div>{page && <><div className="builder-blocks">{page.blocks.map((item, index) => <div className={"builder-block " + (item.id === selectedBlockId ? "selected" : "")} key={item.id} draggable onDragStart={() => setDragged(index)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorder(index)} onClick={() => setSelectedBlockId(item.id)}><span className="drag-handle">⠿</span><span><b>{item.type}</b><small>{item.content || "Empty block"}</small></span><button className="text-button" onClick={(event) => { event.stopPropagation(); save({ ...page, blocks: page.blocks.filter((candidate) => candidate.id !== item.id) }); if (selectedBlockId === item.id) setSelectedBlockId(""); }}>Delete</button></div>)}</div><div className="builder-add"><select value={newType} onChange={(event) => setNewType(event.target.value as Block["type"])}><option value="text">Text</option><option value="image">Image</option><option value="button">Button</option><option value="columns">Columns</option><option value="divider">Divider</option><option value="html">HTML</option></select><input value={newContent} onChange={(event) => setNewContent(event.target.value)} placeholder="Add a block…" /><button className="primary-button" disabled={!newContent.trim()} onClick={addBlock}>Add block</button></div></>}</section>
      <aside className="card builder-inspector"><div className="card-heading"><div><p className="eyebrow">INSPECTOR</p><h2>{block ? "Block properties" : "Page properties"}</h2></div></div>{block ? <div className="inspector-form"><label>Content<textarea rows={5} value={block.content} onChange={(event) => updateBlock({ ...block, content: event.target.value })} /></label><label>Alignment<select value={String(block.settings?.align || "left")} onChange={(event) => updateBlock({ ...block, settings: { ...block.settings, align: event.target.value } })}><option>left</option><option>center</option><option>right</option></select></label><label>Color<input type="color" value={String(block.settings?.color || "#202326")} onChange={(event) => updateBlock({ ...block, settings: { ...block.settings, color: event.target.value } })} /></label>{block.type === "button" && <label>Link URL<input value={String(block.settings?.url || "/")} onChange={(event) => updateBlock({ ...block, settings: { ...block.settings, url: event.target.value } })} /></label>}</div> : page ? <div className="inspector-form"><label>SEO title<input value={String(page.metadata?.seoTitle || page.title)} onChange={(event) => save({ ...page, metadata: { ...page.metadata, seoTitle: event.target.value } })} /></label><label>SEO description<textarea rows={4} value={String(page.metadata?.seoDescription || "")} onChange={(event) => save({ ...page, metadata: { ...page.metadata, seoDescription: event.target.value } })} /></label><p className="subhead">Select a block on the canvas to edit its visual properties.</p></div> : <p className="subhead inspector-empty">Create or select a page to begin.</p>}</aside>
    </div>
    <section className="card visual-preview-card" style={{ marginTop: 16 }}><div className="card-heading"><div><p className="eyebrow">LIVE PREVIEW</p><h2>Responsive canvas</h2></div><div className="preview-device-pills"><button className={previewWidth === "1180px" ? "selected" : ""} onClick={() => setPreviewWidth("1180px")}>Desktop</button><button className={previewWidth === "768px" ? "selected" : ""} onClick={() => setPreviewWidth("768px")}>Tablet</button><button className={previewWidth === "390px" ? "selected" : ""} onClick={() => setPreviewWidth("390px")}>Mobile</button></div></div><div className="visual-preview" style={{ maxWidth: previewWidth }}>{page?.blocks.length ? page.blocks.map((item) => <div className="visual-preview-block" key={item.id} style={{ textAlign: (String(item.settings?.align || "left") as "left" | "center" | "right"), color: String(item.settings?.color || "#202326") }}>{item.type === "button" ? <span className="visual-preview-button">{item.content}</span> : item.type === "image" ? <img className="visual-preview-image" src={item.content} alt="" /> : item.type === "divider" ? <hr /> : <div className={item.settings?.variant === "hero" ? "visual-preview-hero" : "visual-preview-copy"}>{item.content}</div>}</div>) : <p className="subhead">Add a block to preview the page.</p>}</div></section>
    <div className="lower-grid" style={{ marginTop: 16 }}><section className="card relation-card"><div className="card-heading"><div><p className="eyebrow">TEMPLATES</p><h2>Reusable patterns</h2></div></div>{templates.map((template) => <div className="taxonomy-summary" key={template.id}><div><b>{template.name}</b><small>{template.blocks.length} blocks · {template.description}</small></div><button className="text-button" onClick={() => apply(template)}>Use</button><button className="text-button" onClick={() => removeTemplate(template)}>Delete</button></div>)}<div className="builder-add"><input value={templateName} onChange={(event) => setTemplateName(event.target.value)} placeholder="Template name" /><button className="primary-button" disabled={!page || !templateName.trim()} onClick={() => { if (!page) return; createTemplate({ id: id("tpl_"), name: templateName.trim(), slug: templateName.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-"), description: "Saved from visual canvas", blocks: page.blocks }); setTemplateName(""); }}>Save template</button></div></section></div>
  <section className="card relation-card" style={{ marginTop: 16 }}><div className="card-heading"><div><p className="eyebrow">DESIGN SYSTEM</p><h2>Active layout rules</h2></div></div>{layouts[0] && <div className="builder-add"><label>Max width<input value={layouts[0].rules.maxWidth} onChange={(event) => updateLayout({ ...layouts[0], rules: { ...layouts[0].rules, maxWidth: event.target.value } })} /></label><label>Spacing<input value={layouts[0].rules.spacing} onChange={(event) => updateLayout({ ...layouts[0], rules: { ...layouts[0].rules, spacing: event.target.value } })} /></label><label>Accent<input type="color" value={layouts[0].rules.accent} onChange={(event) => updateLayout({ ...layouts[0], rules: { ...layouts[0].rules, accent: event.target.value } })} /></label></div>}</section></div>;
}
