import { defineTool } from '@nekuda/webmcp-sdk';
export type Entry={id:string;title:string;type:string;status:'Published'|'Draft';updated:string;relation:string};
export type ContentType={icon:string;name:string;count:number;tone:string;desc:string;slug:string;fields:string[]};
export type Term={id:string;name:string;slug:string;parent:string|null;description?:string};
export type Taxonomy={name:string;slug:string;hierarchical:boolean;terms:Term[]};
export type State={entries:Entry[];setEntries:(v:Entry[]|((x:Entry[])=>Entry[]))=>void;contentTypes:ContentType[];setContentTypes:(v:ContentType[]|((x:ContentType[])=>ContentType[]))=>void;taxonomies:Taxonomy[];setTaxonomies:(v:Taxonomy[]|((x:Taxonomy[])=>Taxonomy[]))=>void;activeType:string;setActiveType:(v:string)=>void;createEntry:(title:string,type:string)=>void;createContentType:(name:string,slug:string,fields:string[])=>void;notify:(v:string)=>void};
export function createTools(s:State){const findTaxonomy=(slug:string)=>s.taxonomies.find(t=>t.slug===slug||t.name===slug);return[
 defineTool({stableKey:'taxonomy.create_taxonomy',name:'create_taxonomy',title:'Crear taxonomía',description:'Crea una taxonomía para clasificar entradas. Puede ser jerárquica para soportar términos padre e hijo.',inputSchema:{type:'object',properties:{name:{type:'string'},slug:{type:'string'},hierarchical:{type:'boolean'}},required:['name','slug'],additionalProperties:false},async execute({name,slug,hierarchical}:{name:string;slug:string;hierarchical?:boolean}){const normalizedSlug=slug.trim().toLowerCase();if(!normalizedSlug||!/^[a-z0-9-]+$/.test(normalizedSlug))throw Error('El slug debe usar letras minúsculas, números o guiones');if(findTaxonomy(normalizedSlug))throw Error('La taxonomía ya existe');const next={name:name.trim(),slug:normalizedSlug,hierarchical:Boolean(hierarchical),terms:[]};s.setTaxonomies(current=>[...current,next]);return{status:'created',name:next.name,slug:normalizedSlug,hierarchical:next.hierarchical,ui_effect:'taxonomy_created'}}}),
 defineTool({stableKey:'taxonomy.create_term',name:'create_term',title:'Crear término',description:'Crea un término dentro de una taxonomía existente, con soporte para jerarquías.',inputSchema:{type:'object',properties:{taxonomy:{type:'string'},name:{type:'string'},slug:{type:'string'},parent:{type:['string','null']},description:{type:'string'}},required:['taxonomy','name','slug'],additionalProperties:false},async execute({taxonomy,name,slug,parent,description}:{taxonomy:string;name:string;slug:string;parent?:string|null;description?:string}){const model=findTaxonomy(taxonomy);if(!model)throw Error('Taxonomía no encontrada');const normalizedSlug=slug.trim().toLowerCase();if(model.terms.some(t=>t.slug===normalizedSlug))throw Error('El término ya existe');if(parent&&!model.terms.some(t=>t.id===parent||t.slug===parent))throw Error('Término padre no encontrado');const term={id:'term_'+Math.random().toString(16).slice(2,8).toUpperCase(),name:name.trim(),slug:normalizedSlug,parent:parent||null,description};s.setTaxonomies(current=>current.map(t=>t.slug===model.slug?{...t,terms:[...t.terms,term]}:t));return{status:'created',taxonomy:model.slug,term,ui_effect:'term_created'}}}),
 defineTool({stableKey:'taxonomy.list_terms',name:'list_taxonomy_terms',title:'Listar términos',description:'Lista términos de una taxonomía para que el agente pueda navegar categorías, etiquetas y jerarquías.',inputSchema:{type:'object',properties:{taxonomy:{type:'string'}},required:['taxonomy'],additionalProperties:false},async execute({taxonomy}:{taxonomy:string}){const model=findTaxonomy(taxonomy);if(!model)throw Error('Taxonomía no encontrada');return{taxonomy:model.name,slug:model.slug,hierarchical:model.hierarchical,terms:model.terms,count:model.terms.length}}}),
 defineTool({stableKey:'taxonomy.set_entry_terms',name:'set_entry_terms',title:'Asignar términos',description:'Asigna términos existentes a una entrada y deja visible la relación en la interfaz.',inputSchema:{type:'object',properties:{entryId:{type:'string'},taxonomy:{type:'string'},terms:{type:'array',items:{type:'string'}}},required:['entryId','taxonomy','terms'],additionalProperties:false},async execute({entryId,taxonomy,terms}:{entryId:string;taxonomy:string;terms:string[]}){const model=findTaxonomy(taxonomy);if(!model)throw Error('Taxonomía no encontrada');const resolved=terms.map(value=>model.terms.find(t=>t.id===value||t.slug===value||t.name===value));if(resolved.some(t=>!t))throw Error('Uno o más términos no existen');const entry=s.entries.find(e=>e.id===entryId);if(!entry)throw Error('Entrada no encontrada');const label=model.name+': '+resolved.map(t=>t!.name).join(', ');s.setEntries(s.entries.map(e=>e.id===entryId?{...e,relation:entry.relation==='No relations yet'?label:entry.relation+' · '+label,updated:'Just now'}:e));return{entryId,taxonomy:model.slug,terms:resolved.map(t=>t!.slug),ui_effect:'terms_assigned'}}}),
 defineTool({stableKey:'schema.create_content_type',name:'create_content_type',title:'Crear tipo de contenido',description:'Crea un nuevo tipo de entrada con slug y campos. El tipo queda disponible para futuras entradas y se refleja en el schema.',inputSchema:{type:'object',properties:{name:{type:'string'},slug:{type:'string'},fields:{type:'array',items:{type:'string'}}},required:['name','slug'],additionalProperties:false},async execute({name,slug,fields}:{name:string;slug:string;fields?:string[]}){s.createContentType(name,slug,fields||['title']);return{status:'created',name,slug,fields:fields||['title'],ui_effect:'schema_updated'}}}),
 defineTool({stableKey:'content.list_entries',name:'list_content_entries',title:'Listar entradas',description:'Devuelve entradas del workspace, filtradas opcionalmente por tipo o búsqueda.',inputSchema:{type:'object',properties:{type:{type:'string'},query:{type:'string'}},additionalProperties:false},async execute({type,query}:{type?:string;query?:string}){const result=s.entries.filter(e=>(!type||e.type===type)&&(!query||((e.title+' '+e.relation).toLowerCase().includes(query.toLowerCase()))));return{entries:result,count:result.length}}}),
 defineTool({stableKey:'content.create_entry',name:'create_content_entry',title:'Crear entrada',description:'Crea un borrador usando cualquier tipo de contenido definido en el schema.',inputSchema:{type:'object',properties:{title:{type:'string'},type:{type:'string'}},required:['title','type'],additionalProperties:false},async execute({title,type}:{title:string;type:string}){if(!s.contentTypes.some(t=>t.name===type||t.slug===type))throw Error('Tipo de contenido no encontrado');const resolved=s.contentTypes.find(t=>t.name===type||t.slug===type);s.createEntry(title,resolved?.name||type);return{status:'created',title,type:resolved?.name||type,ui_effect:'entry_created'}}}),
 defineTool({stableKey:'content.set_type_filter',name:'filter_content_type',title:'Filtrar por tipo',description:'Actualiza el filtro visible de entradas.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['All content','Article','Author','Project']}},required:['type'],additionalProperties:false},async execute({type}:{type:string}){s.setActiveType(type);return{activeType:type,ui_effect:'filter_updated'}}}),
 defineTool({stableKey:'content.publish_entry',name:'publish_content_entry',title:'Publicar entrada',description:'Publica una entrada existente por su id.',inputSchema:{type:'object',properties:{entryId:{type:'string'}},required:['entryId'],additionalProperties:false},async execute({entryId}:{entryId:string}){const item=s.entries.find(e=>e.id===entryId);if(!item)throw Error('Entrada no encontrada');s.setEntries(s.entries.map(e=>e.id===entryId?{...e,status:'Published',updated:'Just now'}:e));return{entryId,status:'Published',ui_effect:'entry_published'}}}),
 defineTool({stableKey:'content.resolve_relations',name:'resolve_content_relations',title:'Resolver relaciones',description:'Devuelve las conexiones conocidas de una entrada para navegar el grafo de contenido.',inputSchema:{type:'object',properties:{entryId:{type:'string'}},required:['entryId'],additionalProperties:false},async execute({entryId}:{entryId:string}){const item=s.entries.find(e=>e.id===entryId);if(!item)throw Error('Entrada no encontrada');return{entryId,title:item.title,relations:item.relation,ui_effect:'relations_inspected'}}}),
]};
