import { defineTool } from '@nekuda/webmcp-sdk';
export type Entry={id:string;title:string;type:string;status:'Published'|'Draft';updated:string;relation:string};
export type ContentType={icon:string;name:string;count:number;tone:string;desc:string;slug:string;fields:string[]};
export type State={entries:Entry[];setEntries:(v:Entry[]|((x:Entry[])=>Entry[]))=>void;contentTypes:ContentType[];setContentTypes:(v:ContentType[]|((x:ContentType[])=>ContentType[]))=>void;activeType:string;setActiveType:(v:string)=>void;createEntry:(title:string,type:string)=>void;createContentType:(name:string,slug:string,fields:string[])=>void;notify:(v:string)=>void};
export function createTools(s:State){return[
 defineTool({stableKey:'schema.create_content_type',name:'create_content_type',title:'Crear tipo de contenido',description:'Crea un nuevo tipo de entrada con slug y campos. El tipo queda disponible para futuras entradas y se refleja en el schema.',inputSchema:{type:'object',properties:{name:{type:'string'},slug:{type:'string'},fields:{type:'array',items:{type:'string'}}},required:['name','slug'],additionalProperties:false},async execute({name,slug,fields}:{name:string;slug:string;fields?:string[]}){s.createContentType(name,slug,fields||['title']);return{status:'created',name,slug,fields:fields||['title'],ui_effect:'schema_updated'}}}),
 defineTool({stableKey:'content.list_entries',name:'list_content_entries',title:'Listar entradas',description:'Devuelve entradas del workspace, filtradas opcionalmente por tipo o búsqueda.',inputSchema:{type:'object',properties:{type:{type:'string'},query:{type:'string'}},additionalProperties:false},async execute({type,query}:{type?:string;query?:string}){const result=s.entries.filter(e=>(!type||e.type===type)&&(!query||((e.title+' '+e.relation).toLowerCase().includes(query.toLowerCase()))));return{entries:result,count:result.length}}}),
 defineTool({stableKey:'content.create_entry',name:'create_content_entry',title:'Crear entrada',description:'Crea un borrador usando cualquier tipo de contenido definido en el schema.',inputSchema:{type:'object',properties:{title:{type:'string'},type:{type:'string'}},required:['title','type'],additionalProperties:false},async execute({title,type}:{title:string;type:string}){if(!s.contentTypes.some(t=>t.name===type||t.slug===type))throw Error('Tipo de contenido no encontrado');const resolved=s.contentTypes.find(t=>t.name===type||t.slug===type);s.createEntry(title,resolved?.name||type);return{status:'created',title,type:resolved?.name||type,ui_effect:'entry_created'}}}),
 defineTool({stableKey:'content.set_type_filter',name:'filter_content_type',title:'Filtrar por tipo',description:'Actualiza el filtro visible de entradas.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['All content','Article','Author','Project']}},required:['type'],additionalProperties:false},async execute({type}:{type:string}){s.setActiveType(type);return{activeType:type,ui_effect:'filter_updated'}}}),
 defineTool({stableKey:'content.publish_entry',name:'publish_content_entry',title:'Publicar entrada',description:'Publica una entrada existente por su id.',inputSchema:{type:'object',properties:{entryId:{type:'string'}},required:['entryId'],additionalProperties:false},async execute({entryId}:{entryId:string}){const item=s.entries.find(e=>e.id===entryId);if(!item)throw Error('Entrada no encontrada');s.setEntries(s.entries.map(e=>e.id===entryId?{...e,status:'Published',updated:'Just now'}:e));return{entryId,status:'Published',ui_effect:'entry_published'}}}),
 defineTool({stableKey:'content.resolve_relations',name:'resolve_content_relations',title:'Resolver relaciones',description:'Devuelve las conexiones conocidas de una entrada para navegar el grafo de contenido.',inputSchema:{type:'object',properties:{entryId:{type:'string'}},required:['entryId'],additionalProperties:false},async execute({entryId}:{entryId:string}){const item=s.entries.find(e=>e.id===entryId);if(!item)throw Error('Entrada no encontrada');return{entryId,title:item.title,relations:item.relation,ui_effect:'relations_inspected'}}}),
]};
